CREATE TABLE requirement (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_key VARCHAR(255)                            NOT NULL,
    space_id   BIGINT                                  NOT NULL,
    key        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_requirement PRIMARY KEY (id)
);
